const Alphabet = [
    {
        id: 1,
        letter: 'A',
        disabled: false,
        validity: false,
    },
    {
        id: 2,
        letter: 'B',
        disabled: false,
        validity: false,
    },
    {
        id: 3,
        letter: 'C',
        disabled: false,
        validity: false,
    },
    {
        id: 4,
        letter: 'D',
        disabled: false,
        validity: false,
    },
    {
        id: 5,
        letter: 'E',
        disabled: false,
        validity: false,
    },
    {
        id: 6,
        letter: 'F',
        disabled: false,
        validity: false,
    },
    {
        id: 7,
        letter: 'G',
        disabled: false,
        validity: false,
    },
    {
        id: 8,
        letter: 'h',
        disabled: false,
        validity: false,
    },
    {
        id: 9,
        letter: 'I',
        disabled: false,
        validity: false,
    },
    {
        id: 10,
        letter: 'J',
        disabled: false,
        validity: false,
    },
    {
        id: 11,
        letter: 'K',
        disabled: false,
        validity: false,
    },
    {
        id: 12,
        letter: 'L',
        disabled: false,
        validity: false,
    },
    {
        id: 13,
        letter: 'M',
        disabled: false,
        validity: false,
    },
    {
        id: 14,
        letter: 'N',
        disabled: false,
        validity: false,
    },
    {
        id: 15,
        letter: 'O',
        disabled: false,
        validity: false,
    },
    {
        id: 16,
        letter: 'P',
        disabled: false,
        validity: false,
    },
    {
        id: 17,
        letter: 'Q',
        disabled: false,
        validity: false,
    },
    {
        id: 18,
        letter: 'R',
        disabled: false,
        validity: false,
    },
    {
        id: 19,
        letter: 'S',
        disabled: false,
        validity: false,
    },
    {
        id: 20,
        letter: 'T',
        disabled: false,
        validity: false,
    },
    {
        id: 21,
        letter: 'U',
        disabled: false,
        validity: false,
    },
    {
        id: 22,
        letter: 'V',
        disabled: false,
        validity: false,
    },
    {
        id: 23,
        letter: 'W',
        disabled: false,
        validity: false,
    },
    {
        id: 24,
        letter: 'X',
        disabled: false,
        validity: false,
    },
    {
        id: 25,
        letter: 'Y',
        disabled: false,
        validity: false,
    },
    {
        id: 26,
        letter: 'Z',
        disabled: false,
        validity: false,
    },

];
export default Alphabet;
